securityContext:
  runAsUser: 
  runAsGroup: 
resources: 
  limits:
    memory: 300Mi
    cpu: 300m
  requests:
    memory: 50Mi
    cpu: 100m
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
    http_2xx_insecure:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        tls_config:
          insecure_skip_verify: true
prometheusRule:
  enabled: true
  additionalLabels: {}
  namespace: ""
  rules: 
  - alert: ProbeFailure
    expr: avg_over_time(probe_success[5m]) < 0.95
    for: 1m
    labels:
      severity: error
      namespace: "{{ $labels.namespace }}"
      app: "{{ $labels.app }}"
      component: "{{ $labels.component }}"
    annotations:
      message: "The 'app: {{ $labels.app}}' 'component: {{ $labels.component}}' probe has been failing 5% of the time in the last minute"
