apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

resources:
  - namespace-team-a.yaml
  - limitrange-default.yaml
  - localqueue-pipelines-queue.yaml
  - pipeline.yaml
