---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: username
      type: string
  steps:
    - name: echo
      computeResources: {}
      image: registry.access.redhat.com/ubi10/ubi-micro:latest
      script: |
        echo "Hello $(params.username)!"
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: goodbye
spec:
  params:
    - name: username
      type: string
  steps:
    - name: goodbye
      computeResources: {}
      image: registry.access.redhat.com/ubi10/ubi-micro:latest
      script: |
        echo "Goodbye $(params.username)!"
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-goodbye-pipeline
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        kind: Task
        name: hello
      params:
        - name: username
          value: $(params.username)
    - name: goodbye
      taskRef:
        kind: Task
        name: goodbye
      params:
        - name: username
          value: $(params.username)
      runAfter:
        - hello # Ensures goodbye runs after hello
