apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hello-goodbye-run-
  # name: hello-goodbye-run
  labels:
    # This tells Tekton to wait for Kueue admission
    # defaults made by tekton mutating webhook
    # kueue.x-k8s.io/priority-class: tekton-kueue-default
    # kueue.x-k8s.io/queue-name: pipelines-queue
spec:
  pipelineRef:
    name: hello-goodbye-pipeline
  params:
    - name: username
      value: "Tekton User"
