apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/bookinfo

patches:
- target:
    kind: Gateway
  patch: |
    spec:
      hosts:
        - bookinfo-istio-ingress.apps-crc.testing
- target:
    kind: VirtualService
  patch: |
    spec:
      hosts:
        - bookinfo-istio-ingress.apps-crc.testing
- target:
    kind: Deployment
    name: productpage-v1
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: productpage-v1
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/logLevel: 'rbac:debug,jwt:debug'  # enable RBAC and JWT debug logging
# - target:
#     kind: DestinationRule
#   patch: |-
#     - op: add
#       path: /spec/trafficPolicy
#       value:
#         connectionPool:
#           http:
#             idleTimeout: 60s
#         loadBalancer:
#           simple: LEAST_REQUEST
#         outlierDetection:
#           baseEjectionTime: 30s
#           consecutive5xxErrors: 0
#           consecutiveGatewayErrors: 0
#           consecutiveLocalOriginFailures: 1
#           interval: 5s
#           maxEjectionPercent: 100
#           splitExternalLocalOriginErrors: true
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/replicas
      value: 5
- target:
    kind: Deployment
    name: productpage-v1
  patch: |-
    - op: add
      path: /spec/replicas
      value: 1