apiVersion: v1
kind: Service
metadata:
  name: ingress-gateway-istio-bgp
  namespace: istio-ingress
  annotations:
    metallb.io/address-pool: crc-bgp
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.200.200
  selector:
    gateway.networking.k8s.io/gateway-name: ingress-gateway
  ports:
    - name: https
      appProtocol: https
      port: 443
      protocol: TCP
      targetPort: 443
