namespaceMemberSelector:
  istio.io/rev: ossm-2.5
smcp:
  name: ossm-2-5
  accessLoggingEnabled: true
  version: v2.5
  mode: MultiTenant
  outboundPolicy: REGISTRY_ONLY # ALLOW_ANY
tempo:
  enabled: false
  host: tempo-odf-s3-distributor.tempo-system.svc.cluster.local
kiali:
  enabled: false
  name: kiali-ossm-2-5-istio-system-2-5
