apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: openshift-pipelines
  pruner:
    disabled: false
    keep-since: 2
    resources:
      - pipelinerun
      - taskrun
    schedule: '*/2 * * * *'
  pipeline:
    options:
      disabled: false
      deployments:
        tekton-triggers-core-interceptors:
          spec:
            replicas: 2
            template:
              spec:
                containers:
                  - name: tekton-triggers-core-interceptors
                    resources:
                      limits:
                        cpu: 500m
                        memory: 1Gi
                      requests:
                        cpu: 500m
                        memory: 1Gi
