installRequiredPythonLibraries: false
approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/trevorbox/installplanapproverandverifier:4.16.0 # quay.io/openshift/origin-cli:4.16

operatorGroups:
- name: openshift-kueue-operator
  createNamespace: true

operators:
- channel: stable-v1.3
  installPlanApproval: Manual
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: kueue-operator.v1.3.1
  namespace: openshift-kueue-operator
  installPlanVerifierActiveDeadlineSeconds: 1200
