apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: cryostat
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  workloadSelector:
    labels:
      app: cryostat
      component: cryostat
  egress:
  - hosts:
    - "./*"
    {{- range .Values.targetNamespaces }}
    - {{ printf "%v/*" . }}
    {{- end }}
  outboundTrafficPolicy:
    mode: ALLOW_ANY
