namespaceMemberSelector:
  istio.io/rev: ossm-2.4
smcp:
  name: ossm-2-4
  accessLoggingEnabled: true
  version: v2.4
  mode: MultiTenant
  outboundPolicy: REGISTRY_ONLY # ALLOW_ANY
tempo:
  enabled: false
  host: tempo-odf-s3-distributor.tempo-system.svc.cluster.local
