apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: spring-boot-demo
  repo: https://trevorbox.github.io/helm-charts
  valuesFile: values.yaml
  namespace: spring-boot-demo
  version: ~0.0.13
  releaseName: spring-boot-demo

patches:
  - target:
      kind: Service
      name: spring-boot-demo-headless
    patch: |-
      - op: add
        path: /metadata/annotations/networking.istio.io~1exportTo
        value: cryostat
      - op: remove
        path: /spec/ports/1
