istio:
  enabled: true
ingressgateway:
  host: spring-boot-demo-istio-ingress.apps-crc.testing
replicaCount: 1
cryostat:
  agent:
    enabled: false
  jmx:
    enabled: false
  headlessService:
    enabled: true
    ports:
    - name: cryostat-agent
      protocol: TCP
      appProtocol: tcp
      port: 9977
      targetPort: 9977
    # - name: jfr-jmx
    #   protocol: TCP
    #   appProtocol: tcp
    #   port: 9091
    #   targetPort: 9091
podLabels:
  sidecar.istio.io/inject: "true"
  # operator injection labels
  cryostat.io/log-level: info
  cryostat.io/name: cryostat
  cryostat.io/namespace: cryostat
  cryostat.io/container: spring-boot-demo
  cryostat.io/callback-port: "9977"
podEnv:
  # https://github.com/cryostatio/cryostat-agent#configuration
  - name: CRYOSTAT_AGENT_SMART_TRIGGER_DEFINITIONS
    value: "[HeapMemoryUsagePercent>0.1;TargetDuration>duration(\"30s\")]~profile"
  # - name: CRYOSTAT_AGENT_SMART_TRIGGER_EVALUATION_PERIOD_MS
  #   value: "3600000" # 1 hour
  - name: CRYOSTAT_AGENT_SMART_TRIGGER_EVALUATION_PERIOD_MS
    value: "1000" # 1 second
  # https://github.com/cryostatio/cryostat-agent#harvester-integration
  - name: CRYOSTAT_AGENT_HARVESTER_PERIOD_MS
    value: "3600000" # 1 hour
  - name: CRYOSTAT_AGENT_HARVESTER_MAX_AGE_MS
    value: "3600000" # 1 hour
  - name: CRYOSTAT_AGENT_HARVESTER_MAX_SIZE_B
    value: "104857600" # 100 MB
  - name: CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS
    value: "3600000" # 1 hour
  - name: CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B
    value: "104857600" # 100 MB
  - name: CRYOSTAT_AGENT_HARVESTER_AUTOANALYZE
    value: "false"
  - name: CRYOSTAT_AGENT_HARVESTER_MAX_FILES
    value: "24"

  # - name: CRYOSTAT_AGENT_HARVESTER_TEMPLATE
  #   value: "Profiling"
  # - name: CRYOSTAT_AGENT_SMART_TRIGGER_DEFINITIONS
  #   value: "[(ProcessCpuLoad>0.5||SystemCpuLoad>0.25)&&HeapMemoryUsagePercent>0.1;TargetDuration>duration('1m')]~Continuous"
  # - name: CRYOSTAT_AGENT_SMART_TRIGGER_DEFINITIONS
  #   value: "[ProcessCpuLoad > 0.1 ; TargetDuration > duration(\"30s\")]~profile"
  # - name: CRYOSTAT_AGENT_HARVESTER_PERIOD_MS
  #   value: "1000"
  # - name: CRYOSTAT_AGENT_HARVESTER_TEMPLATE
  #   value: profile
  # - name: JAVA_OPTS_APPEND
  #   # Remove -Duser.dir! Only keep the HeapDumpPath for OOM situations.
  #   value: "-XX:HeapDumpPath=/tmp"

  - name: JAVA_APP_DIR
    value: "/application"

  - name: CRYOSTAT_AGENT_BASE_DIR
    # This tells the Cryostat Agent to use /tmp for its staging files
    value: "/tmp"

  # - name: JAVA_TOOL_OPTIONS
  #   # Add the tmpdir flag here just to be safe, but keep the rest as is
  #   value: "-Djava.io.tmpdir=/tmp"
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
