apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
spec:
  uid: "2aaa2e27-41bd-4e18-a253-2b328390e2bc"
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Tempo
    type: tempo
    access: proxy
    basicAuth: false
    url: https://tempo-minio-dev-gateway.tempo-system.svc.cluster.local:8080/api/traces/v1/dev/tempo
    isDefault: false
    editable: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
      httpHeaderName1: 'Authorization'
      httpHeaderName2: 'X-Scope-OrgID'
    secureJsonData:
      "httpHeaderValue1": "Bearer ${token}" # Notice the brakes around token
      "httpHeaderValue2": "dev"
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-token"
          key: "token"
