apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: operators-installer
  repo: https://redhat-cop.github.io/helm-charts
  valuesFile: values.yaml
  namespace: openshift-gitops
  version: 3.0.1

patches:
  - target:
      kind: Namespace
      name: openshift-pipelines-operator
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-pipelines-operator
        labels:
          openshift.io/cluster-monitoring: "true"