installRequiredPythonLibraries: false
approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/trevorbox/installplanapproverandverifier:4.16.0 # quay.io/openshift/origin-cli:4.16

operatorGroups:
- name: openshift-pipelines-operator
  createNamespace: true

operators:
- channel: latest
  installPlanApproval: Manual
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: openshift-pipelines-operator-rh.v1.21.1
  namespace: openshift-pipelines-operator
  installPlanVerifierActiveDeadlineSeconds: 1200
