apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  # - clusterrole-snapshot-list.yaml
  # - clusterrolebinding-snapshot-list.yaml
  - storagecluster.yaml
  # TODO test without these... test if annotation is actually needed
  # - serviceaccount.yaml
  # - role.yaml
  # - rolebinding.yaml
  # - job-noobaa-access-mode.yaml
