apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: cryostat
spec:
  applicationMenu:
    section: Observability
    imageURL: data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADEElEQVR4AXxTWUhUURj+z7nXnJkclyBHWzFaSEfDiBYpUCvTgqTGGRQKUtMx6cF6sFBILGhBK62H1FEzMsRx60FMWyyJFKLSbNSiFJxSUXF3xpGZe//OHVF8EA+ce/7l+9ePS2GVk2A0FcZX/ihZBQIrJtAajVxSlSmVEMITAF6StUbkVkpEVzIqhe0qu4DXBVE8JyDEMjnDg+v0XQnrTKA3miKzjKY1rOWGi1VdR0rj9g5u9FLGAsIw62B0s+fauGLNnn/62p5DDNMkYfW1pkgpIU2ra/ecF7GoH7ETEQNZ1aiCL8PZ3nKa3PGmtrHz3cuGdQousejzyC27XYhCBLUZsWPejsVXjKZ1NO9M8KSb3OUgqzQtImwCQsLzc+/SMkOhQ7BMJgkzE0llxU+EvNw7VAQIFxE3ABCrkhcPPtSpx50jzNkcx5nRjxJSPWb+/d0yY42MPhyU+KHwJrwvzIbokD0JsxZr5Jj5j4kSqELALRaBngB2nAmmCVTMkgCfA9u8K1UKlwlm35mRoAFNeg6cSrsNH9t/goDiDh8FNxXip6qxkB7fzUCeM9wCjV4TNvTvAidPPMdRIMi6ldwLl+2GmQhSQhAZt/5dWhxiMZKXSh+HhyzO7G8abOsb1pinrO6AtPfeszqoy0mHhvxMCN0XAJQjvQMzNo+2vqHT/f5dA4Kn63kp1plAIeffMsUsca7auitYLnd9Vd3ytTRUnwXhKVlQ1/KtTCGXNa332xUkIokjBAYUvOw1iwEnjbNzjlameEkOINB8NT0D45Mv8SB3KxFl7iUXklIg7Vom2x1pZpghNqByxm5rXaLRhcPLbkqZmjm7ORAb9ftVN0ZtDkNwRMyx4IizEeM2LE3Z553hykMj20OP0t01yIXjU5doNGgD6x+f3DH/VBcYYdAFtSTXdPsOjFnLAWADuz5/Jy0vUoy/NhZo1J9KdeqjEtag3V3PfAssSMLyOyHsHuF5+oBytJxVrGB/0X3V+sHh5ZhF2bnERWXxrdIRoTgm4BEg2tngjpLYwPzssDDHon/5+x8AAP//KHXlCwAAAAZJREFUAwD5b1EjD0CjOQAAAABJRU5ErkJggg==
  href: https://cryostat-cryostat.apps-crc.testing
  location: ApplicationMenu
  text: "Cryostat"
