---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-kube-state-metrics
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    openshift.io/cluster-monitoring: "true"
