installRequiredPythonLibraries: false
approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/trevorbox/installplanapproverandverifier:4.16.0 # quay.io/openshift/origin-cli:4.16

operatorGroups:
- name: quay-operator
  createNamespace: true

operators:
- channel: stable-3.17
  installPlanApproval: Manual
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  csv: quay-operator.v3.17.3
  namespace: quay-operator
  installPlanVerifierActiveDeadlineSeconds: 1200
