apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 2.4.1  # It is recommended to pin to a specific version
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true