apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: minio-dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storage:
    secret:
      name: tempo-s3
      type: s3
    tls:
      enabled: true
      caName: tempo-s3-serving-cabundle
