apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: odf-s3
spec:
  storageSize: 30Gi
  storage:
    secret:
      name: tempo-s3
      type: s3
    tls:
      enabled: true
      caName: tempo-s3-serving-cabundle
  resources:
    total:
      limits:
        memory: 6Gi
        cpu: '4'
  tenants:
    mode: openshift
    authentication: 
      - tenantName: dev
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
      - tenantName: prod
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
  # observability:
  #   metrics:
  #     createServiceMonitors: true
  # observability:
  #   metrics:
  #     createPrometheusRules: true
  template:
    gateway:
      enabled: true
      rbac:
        enabled: true 
    queryFrontend:
      jaegerQuery: 
        # enabled: true
        enabled: false
        # ingress:
        #   route:
        #     termination: edge
        #   type: route