apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: team-a-cluster-queue
spec:
  namespaceSelector: {} # Allows any namespace to point here, or restrict it to team-a
  resourceGroups:
  - coveredResources:
    - tekton.dev/pipelineruns
    flavors:
    - name: default
      resources:
      - name: "tekton.dev/pipelineruns"
        nominalQuota: 2
