apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kueue-cluster.yaml
- clusterqueue-team-a-cluster-queue.yaml
- resourceflavor-default.yaml

namespace: openshift-kueue-operator
