apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  annotations:
    argocd.argoproj.io/sync-wave: '4'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  tracing:
  - providers:
    - name: tempo
    randomSamplingPercentage: 100
  metrics:
  - providers:
    - name: prometheus
      overrides:
        - match:
            metric: ALL_METRICS
            mode: CLIENT_AND_SERVER
          tagOverrides:
            source_principal:
              operation: REMOVE
            destination_principal:
              operation: REMOVE
            grpc_response_status:
              operation: REMOVE
            request_protocol:
              operation: REMOVE
            connection_security_policy:
              operation: REMOVE
        - match:
            metric: ALL_METRICS
            mode: CLIENT
          disabled: true
        - match:
            metric: REQUEST_BYTES
            mode: CLIENT_AND_SERVER
          disabled: true
        - match:
            metric: RESPONSE_BYTES
            mode: CLIENT_AND_SERVER
          disabled: true
